### ISSUE TITLE
Would Send you info about ISE (IllegalStateException) with World Generation

### ISSUE THREAD

**Issue by suerion** [ITsMrToad/ToadLib-mod#4]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Fabric

### Describe the bug

Hey, i had a lot ob world Generation Mods here, it does not is a reall issue, but i think it should be fixed also,

Could you look on this error?
```
[14:17:48] [Worker-Main-8/ERROR]: Couldn't read tag list toadlib:is_plainslike from toadlib:tags/worldgen/biome/is_plainslike.json in data pack toadlib
java.lang.IllegalStateException: Not a JSON object: null
	at com.mojang.serialization.DataResult$Error.md0d6e54$owo$lambda$addStackTraceToException$0$0(DataResult.java:565) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
	at net.minecraft.class_3503.method_33174(class_3503.java:53) ~[server-intermediary.jar:?]
	at net.minecraft.class_3503.method_33176(class_3503.java:128) ~[server-intermediary.jar:?]
	at net.minecraft.class_3505.method_33181(class_3505.java:46) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

### Steps to reproduce

Start Server
Server Log ( Line 2229)
https://mclo.gs/sTBJhnd

### What version of the toadlib are you using?

toadlib 1.1.6

**Comment by ITsMrToad** [comment]
I was probably able to fix this in 1.1.7....

**Comment by suerion** [comment]
Thanks, i will test it then

**Comment by suerion** [comment]
@ITsMrToad is the fix also for 1.21.1? you had released the mod for 1.20–1.20.4

My issue is on 1.21.1, but could be fixed in all other versions :)

Sorry, had forgotten to write it here
